#!/usr/bin/env python3
"""Step 30: freeze the paper's numbers — Phase 2 of `plans/active/publication.md`.

Every draft section must quote from ONE table. Before this existed, each section
recomputed its own figures from whatever was current when it was written, which
is how the draft came to carry the retired chained series' 312 peak alongside
§3's post-exclusion GEKS numbers.

Source of truth is `docs/data.json`, which the site publishes. Phase 1 (D1-D4,
closed 2026-08-06) changed no published figure -- MIN_MATCH stays 3, the window
stays 2020Q1, the reputation band is an ADDITIONAL series, and D4 removes the
elasticity table rather than altering the index -- so no pipeline re-run was
needed and data.json stands as generated 2026-07-31.

Writes `data/pilot/paper-numbers.md` (the table sections quote) and
`data/pilot/paper-numbers.json` (machine-readable, for the render check).

Run:  python3 code/30-freeze-numbers.py
"""
import json
import math
from pathlib import Path

BASE = Path(__file__).resolve().parent.parent
DATA = BASE / "docs" / "data.json"
OUT_MD = BASE / "data" / "pilot" / "paper-numbers.md"
OUT_JSON = BASE / "data" / "pilot" / "paper-numbers.json"

d = json.loads(DATA.read_text())
CATS = d["categories"]
Q = d["months"]
LABEL = d["labels"]


def hw(se):
    """+/-% half width at 95%.

    1.96*se on the LOG scale, which is the convention `docs/ipi.js` publishes
    (`halfWidth = se => 196 * se`). Kept identical so the paper and the site
    cannot quote different bands for the same cell. The exact CI on the level is
    asymmetric -- see `ci()` -- and the site shows that form in its tooltips."""
    return 196.0 * se if se else None


def ci(se, level):
    """Exact asymmetric 95% interval on the index LEVEL (site tooltip form)."""
    if not se or level is None:
        return None, None
    return level * math.exp(-1.96 * se), level * math.exp(1.96 * se)


def last_valid(series):
    """(quarter, value) for the last non-null entry."""
    for i in range(len(series) - 1, -1, -1):
        if series[i] is not None:
            return Q[i], series[i]
    return None, None


rows = []
for c in CATS:
    nq, nom = last_valid(d["index_geks"][c])
    rq, real = last_valid(d["index_geks_real"][c])
    se_series = d["index_geks_se"][c]
    se = se_series[Q.index(nq)] if nq else None
    rows.append({
        "category": c,
        "label": LABEL[c],
        "panel_gigs": d["panel_gigs"][c],
        "weight": d["weights"][c],
        "terminal_quarter": nq,
        "index_nominal": nom,
        "index_real": real,
        "delta_nominal_pct": d["delta_geks"][c],
        "delta_real_pct": d["delta_geks_real"][c],
        "se_ln": se,
        "band_pct": hw(se),
        "ci_level": ci(se, nom),
        "meets_5pct": (hw(se) is not None and hw(se) <= 5.0),
    })

cq, cnom = last_valid(d["composite_geks"])
_, creal = last_valid(d["composite_geks_real"])
cse = d["composite_geks_se"][Q.index(cq)]
composite = {
    "terminal_quarter": cq,
    "index_nominal": cnom,
    "index_real": creal,
    "delta_nominal_pct": d["delta_geks"]["composite"],
    "delta_real_pct": d["delta_geks_real"]["composite"],
    "se_ln": cse,
    "band_pct": hw(cse),
    "ci_level": ci(cse, cnom),
    "meets_5pct": hw(cse) <= 5.0,
}
cpi_q, cpi_last = last_valid(d["cpi"])
cpi_change = cpi_last - 100.0

frozen = {
    "source": "docs/data.json",
    "data_generated": d["generated"],
    "base_period": d["base_period"],
    "window": f"{Q[0]}-{Q[-1]}",
    "n_quarters": len(Q),
    "categories": rows,
    "composite": composite,
    "cpi_change_pct": cpi_change,
    "adequacy_rule_pct": 5.0,
    # measured 2026-08-06, code/27-reputation-band.py (D2)
    "reputation_band": {"raw_pct": 79.0, "adjusted_pct": 39.7,
                        "beta": 0.1068, "beta_se": 0.0201, "beta_t": 5.32,
                        "beta_pooled": True},
}
OUT_JSON.write_text(json.dumps(frozen, indent=2) + "\n")

n_fail = sum(1 for r in rows if not r["meets_5pct"])
L = []
L.append("# Frozen paper numbers")
L.append("")
L.append(f"**Source:** `{frozen['source']}` (generated {frozen['data_generated']}). "
         f"**Base:** {frozen['base_period']} = 100. "
         f"**Window:** {frozen['window']} ({frozen['n_quarters']} quarters).")
L.append("")
L.append("Generated by `code/30-freeze-numbers.py`. **Every draft section quotes from "
         "this file. No section computes its own figures.** Phase 1 of the publication "
         "plan (D1-D4) changed no published figure, so no pipeline re-run was required.")
L.append("")
L.append("Bands are 1.96 x the bootstrap SE of the **log** level at each category's "
         "terminal quarter (200 replications, gigs resampled with replacement) -- the "
         "same convention `docs/ipi.js` publishes, so the paper and the site cannot "
         "quote different bands for the same cell. The exact interval on the level is "
         "asymmetric and is given in the last column.")
L.append("")
L.append("## Composite and categories")
L.append("")
L.append("| Series | Panel gigs | Weight | Terminal | Nominal | Real | "
         "Nominal Δ | Real Δ | ±95% | Meets ±5% | 95% CI on nominal level |")
L.append("|---|---:|---:|---|---:|---:|---:|---:|---:|:--:|---|")
lo, hi = composite["ci_level"]
L.append(f"| **Composite** | — | 1.000 | {composite['terminal_quarter']} | "
         f"{composite['index_nominal']:.1f} | {composite['index_real']:.1f} | "
         f"{composite['delta_nominal_pct']:+.1f}% | {composite['delta_real_pct']:+.1f}% | "
         f"±{composite['band_pct']:.1f}% | {'yes' if composite['meets_5pct'] else 'NO'} | "
         f"{lo:.1f}–{hi:.1f} |")
for r in sorted(rows, key=lambda x: -x["weight"]):
    lo, hi = r["ci_level"]
    L.append(f"| {r['label']} | {r['panel_gigs']} | {r['weight']:.3f} | "
             f"{r['terminal_quarter']} | {r['index_nominal']:.1f} | {r['index_real']:.1f} | "
             f"{r['delta_nominal_pct']:+.1f}% | {r['delta_real_pct']:+.1f}% | "
             f"±{r['band_pct']:.1f}% | {'yes' if r['meets_5pct'] else 'NO'} | "
             f"{lo:.1f}–{hi:.1f} |")
L.append("")
L.append(f"CPI-U over the same window: **{cpi_change:+.1f}%**. "
         f"Categories missing the ±5% adequacy rule: **{n_fail} of {len(rows)}**.")
L.append("")
L.append("## Reputation-adjusted band (D2, `code/27-reputation-band.py`)")
L.append("")
rb = frozen["reputation_band"]
L.append(f"Composite {frozen['window']}: **raw {rb['raw_pct']:+.1f}%**, "
         f"**reputation-adjusted {rb['adjusted_pct']:+.1f}%**. "
         f"β pooled at **{rb['beta']:+.4f}** (se {rb['beta_se']:.4f}, t {rb['beta_t']:.2f}), "
         f"gig-clustered. The adjusted figure is a lower bound, not a correction: reviews "
         f"are cumulative sales, so β absorbs demand as well as reputation. Raw is the "
         f"headline; the pair is published as a range, and its floor is soft "
         f"(≈+50% to +28% across β's own 95% CI).")
L.append("")
OUT_MD.write_text("\n".join(L) + "\n")

print(f"Wrote {OUT_MD.relative_to(BASE)} and {OUT_JSON.relative_to(BASE)}")
print(f"  composite {composite['delta_nominal_pct']:+.1f}% nominal / "
      f"{composite['delta_real_pct']:+.1f}% real, ±{composite['band_pct']:.1f}%")
print(f"  {n_fail} of {len(rows)} categories miss the ±5% rule")
print(f"  CPI-U {cpi_change:+.1f}%")
